repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format --check
        language: python
        additional_dependencies: ["ruff==0.15.20"]
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: ruff check --force-exclude
        language: python
        additional_dependencies: ["ruff==0.15.20"]
        types_or: [python, pyi]

      - id: detect-secrets
        name: detect secrets
        entry: detect-secrets-hook --baseline .secrets.baseline
        language: python
        additional_dependencies: ["detect-secrets==1.5.0"]
        exclude: ^src/\.env\.example$
